### ISSUE TITLE
Issue: Error Code 422 When Sending Chat Messages Containing Images in Azure OpenAI Pipeline

### ISSUE THREAD

**Issue by Wenlin88** [open-webui/pipelines#103]
When using the Azure OpenAI pipeline, attempting to send a chat message that contains an image results in a 422 Un processable Entity error. This issue occurs most probably because the current OpenAIChatMessage schema does not support image inputs, leading to validation failures.

Open WebUI Version
v0.3.5

Pipelines
commit df2124e

**Comment by justinh-rahb** [comment]
Vision can be disabled per model in **Workspace > Models**:

![Screenshot_20240620-052430.png](https://github.com/open-webui/pipelines/assets/52832301/c923104f-bff0-41dd-88ba-3dcc015306d7)

**Comment by Wenlin88** [comment]
My current understanding is that it is not coming from this, but more from the fact that image content is in dictionary from WebUI side. 

Due that I added to schemas.py:

``` python
class ImageContent(BaseModel):
    type: str
    image_url: dict

class TextContent(BaseModel):
    type: str
    text: str

class MessageContent(RootModel):
    root: Union[TextContent, ImageContent]
```

**Comment by Wenlin88** [comment]
#104
