### ISSUE TITLE
can't use vision functino of claude 3.5

### ISSUE THREAD

**Issue by TSECP** [open-webui/pipelines#114]
based on the examples/pipelines/providers folder, i used the template file of anthropic_manifold_pipeline.py and add the anthropic API key into it. 
I can use the chat function for the Claude 3.5 model, when i try to use the vision fucntion of model, it's shows the error message: there is the problem of connection to anthropic/claude-3.5-sonnet, load failed. 

Is there anyone could help me to solve this problem. Any setting adjustment in that template file? 

Thx for your attention and help.

**Comment by justinh-rahb** [comment]
I'll look into updating this to support vision. Stay tuned.

**Comment by justinh-rahb** [comment]
Hey guys I've already ported this Pipeline to WebUI Functions as well as added the image functionality. I'll backport that here hopefully tonight.

**Comment by justinh-rahb** [comment]
Fixed:
- #124
