### ISSUE TITLE
Can't use document upload with Anthropic models

### ISSUE THREAD

**Issue by julwrites** [open-webui/pipelines#121]
I've set up the pipeline and it works for text-text interaction, but when I provide a document or web-link, it fails with the following error: 

```
Uh-oh! There was an issue connecting to anthropic/claude-3-opus.
Error in input stream
```

Is this a limitation of pipelines, or just not implemented yet for the Anthropic manifold pipeline?

**Comment by julwrites** [comment]
Cool, I saw that but wasn't sure if it would be the same fix. I'll wait for that to be ported and test it out. Thanks! :)

**Comment by justinh-rahb** [comment]
Fixed:
- #124
