### ISSUE TITLE
Uh-oh! There was an issue connecting to Google: Gemini 1.5 Pro Latest. NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by HakaishinShwet** [open-webui/pipelines#123]
This is the error i am getting when i try to use image with promt in google gemini pro 1.5. Is there issue in python script or something else?

**Comment by justinh-rahb** [comment]
Need more log information. That could be anything from wrong key to blocked country.

**Comment by justinh-rahb** [comment]
Resolved by:
- #131
