### ISSUE TITLE
feat: model chaining

### ISSUE THREAD

**Issue by Sooloom** [open-webui/pipelines#13]
I have two models, the first one only supports English, and the second one supports Japanese and English. I would like to have my words translated into English through the second model first, then have a conversation with the first model, and then the first model will submit the response to the second model for translation into Japanese.

Can this function be automatically completed？

**Comment by tjbck** [comment]
Implemented with `filter` pipeline using `inlet`, and `outlet` hooks!

https://github.com/open-webui/pipelines/assets/25473318/4f818d72-adca-4ed0-a2e7-c5d061236f2d



https://github.com/open-webui/pipelines/blob/main/pipelines/examples/libretranlsate_filter_pipeline.py
