### ISSUE TITLE
Anthropic API error - invalid x-api-key

### ISSUE THREAD

**Issue by yblis** [open-webui/pipelines#145]
Hello,

I integrated the Anthropic pipeline available at this link: https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/anthropic_manifold_pipeline.py to test its capabilities. I retrieved the API, but I get this error message when attempting to communicate with the AI Claude 3-5:

`Error: Error code: 401 - {type: error, error: {type: authentication_error, message: invalid x-api-key}}`

Note: The API key is valid.

Please help

**Comment by justinh-rahb** [comment]
you can either start the Pipelines Docker container with environment variable `-e ANTHROPIC_API_KEY=your-api-key` or set it in **Admin Settings > Pipelines** Anthropic valves configuration:

<img width="484" alt="Screenshot 2024-07-01 at 10 12 01 PM" src="https://github.com/open-webui/pipelines/assets/52832301/e1f658ab-88ac-454e-8587-822add548683">

**Comment by yblis** [comment]
Thank you for your response, bur that's exactly what I did.

![image](https://github.com/open-webui/pipelines/assets/10268910/7fa948e6-816d-4f25-8f0d-451832d8735b)

![image](https://github.com/open-webui/pipelines/assets/10268910/802b0117-cd08-4634-a0e2-36af48b7770c)

**Comment by yblis** [comment]
Well, the problem came from my API key, I think there are issues on Anthropic's side, thank you for your help.
