### ISSUE TITLE
Dependencies not being pulled

### ISSUE THREAD

**Issue by DarkIceXD** [open-webui/pipelines#151]
I can't find a way to upload a pipeline with dependencies.
I created this test pipeline:
test.py:
```
"""
title: Test pipline
requirements: llama-index-vector-stores-qdrant
"""

from typing import List, Union, Generator, Iterator

class Pipeline:
    def __init__(self):
        pass
    
    def pipe(
        self, user_message: str, model_id: str, messages: List[dict], body: dict
    ) -> Union[str, Generator, Iterator]:
        return "hello world"
```

Notice the llama-index requirement. I then added the pipeline through the UI and checked the installed modules by doing `docker exec pipelines pip list | grep llama-index-vector-stores-qdrant` and it would't find it. I am not sure if its an issue with Pipelines or WebUI.

I also can't use `PIPELINES_URLS` because i would have to upload the pipeline publicly which isn't an option.

**Comment by Marenz** [comment]
From what I can tell the PIPELINE_URLS is the only way to do this currently. 
But you don't have to upload something publicly for that:

* You can use a [private gist](https://gist.github.com) that only works with you know the link
* You start a minimal http server and host it yourself for the few seconds its starting up, just ask chatgpt or any LLM of your choice to give you a simple single file http server

**Comment by DarkIceXD** [comment]
its kind of hacky. i might look into implementing it myself and opening a PR. as far as i can see its just implementing [this](https://github.com/open-webui/pipelines/blob/98604da8ec79323d02086fd5c5a906f1c190bf6e/start.sh#L85-L105) in python.
