### ISSUE TITLE
wsl: docker installation error

### ISSUE THREAD

**Issue by DavidWang67** [open-webui/pipelines#160]
container starting error, here is the output from running 'docker logs pipelines'

ERROR:    Application startup failed. Exiting.
Loaded module: llamaindex_ollama_pipeline
Loaded module: llamaindex_ollama_github_pipeline
RESET_PIPELINES_DIR is not set to true. No action taken.
PIPELINES_REQUIREMENTS_PATH not specified. Skipping installation of requirements.
PIPELINES_URLS not specified. Skipping pipelines download and installation.
INFO:     Started server process [7]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 211, in lifespan
    await on_startup()
  File "/app/main.py", line 190, in on_startup
    await module.on_startup()
  File "/app/./pipelines/llamaindex_ollama_pipeline.py", line 38, in on_startup
    from llama_index.embeddings.ollama import OllamaEmbedding
ModuleNotFoundError: No module named 'llama_index.embeddings.ollama'

ERROR:    Application startup failed. Exiting.
Loaded module: llamaindex_ollama_pipeline
Loaded module: llamaindex_ollama_github_pipeline

**Comment by muliyul** [comment]
Were you able to resolve this?
