### ISSUE TITLE
Sending Images to OpenAI Not Working

### ISSUE THREAD

**Issue by abhishek-ch** [open-webui/pipelines#161]
I am trying to use gpt-4o to explain images but Openwebui is throwing errr

```Uh-oh! There was an issue connecting to gpt-4o.
text input must be of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
```

![image](https://github.com/user-attachments/assets/ee227b3c-7ae9-4d97-9fdb-fc9559af5a62)

I have tried Pipelines with Manifold and the openAI pipeline but none of them worked.

**Comment by nkeilar** [comment]
@abhishek-ch What was the issue here? I'm having a similar issue
