### ISSUE TITLE
The pipeline libretranslate translates automatically and not let user read the original answer so it will be good if you supports switching button or show translation in another box like chatgpt

### ISSUE THREAD

**Issue by Llamadouble999q** [open-webui/pipelines#176]
Chatgpt translation plugin shows the translation under the llm’s answer with its own box if user click the button it shows the translation. But the open webui pipeline translation function it doesnt let user to review the original answer of llm anymore after it has been translated. It is very uncomfortable and can let user considere not to use if translation is not that much good.
But as you know libretranslate is not really good translator program yet it can cause uncomfortable situation too much often. If you make the switching button for switch between original answer and translated answer then it will be very useful and good.

**Comment by justinh-rahb** [comment]
The LibreTranslate Action Button adds the translation below the original text:
https://openwebui.com/f/jthesse/libretranslate_action

**Comment by Llamadouble999q** [comment]
> The LibreTranslate Action Button adds the translation below the original text: https://openwebui.com/f/jthesse/libretranslate_action

Can you tell me how to connect it exactly? Should i delete libretranslate filter or keep it and add your information too?

**Comment by justinh-rahb** [comment]
This uses the built-in Functions platform of WebUI instead of Pipelines server, but you'll find that even easier to use. Just go to **Workspace > Functions**

**Comment by Llamadouble999q** [comment]
> This uses the built-in Functions platform of WebUI instead of Pipelines server, but you'll find that even easier to use. Just go to **Workspace > Functions**

Thanks but do you know this matter? My pipeline filter has matter with detecting matter, only original libretranslate filter is detecting so i deleted original filter and tried again but still same matter.

**Comment by Llamadouble999q** [comment]
> This uses the built-in Functions platform of WebUI instead of Pipelines server, but you'll find that even easier to use. Just go to **Workspace > Functions**

Yes i did that and also openwebui detect pipeline is working but the filter and action in workspace doesnt be detected

**Comment by JKratto** [comment]
I can't see any button as well. I don't know what I am doing wrong.

**Comment by JKratto** [comment]
I have found it! So under Admin Panel -> Settings -> Models -> some model you want to enable for the translation button. Scroll down and check the tickbox:
Actions
To select actions here, add them to the "Functions" workspace first.

**LibreTranslate Action**

This enables the button (finally) for the specific model only!
