### ISSUE TITLE
Issue: Pipelines Not Detected

### ISSUE THREAD

**Issue by MarlNox** [open-webui/pipelines#18]
### Issue: Pipelines Not Working with Dev Branch of OpenWebUI

**Description:**
When using Pipelines with the latest branch of OpenWebUI, the pipelines remain undetected or unusable. It seems that the running pipelines are not being recognized by OpenWebUI. Any suggestions for a quick fix?

**Steps to Reproduce:**
1. Run the latest dev branch of OpenWebUI (prod branch doesn't seem to have the pipelines option available yet). 
2. Start Pipelines. Put one or more pipelines (filter pipeline ie.) in the pipelines folder. Pipeline is initialized.
3. Add in settings the correct link to the pipelines, it get's recognized as a pipeline and successfully added. 
4. When accessing the Admin Settings - pipeline menu, no pipelines are detected.

**Comment by tjbck** [comment]
Could you try latest for both? Just did some major refacs!

**Comment by MarlNox** [comment]
Updated both repositories OpenWebUI dev, and the Pipelines repository. Pulled the filter pipeline from the example folder, into the pipelines folder. Added the link in Settings. 

Now the Admin Settings Pipelines Panel, shows up empty providing only the title "Manage Pipelines" instead of showing up the error it was previously showing. 
![pipelines](https://github.com/open-webui/pipelines/assets/17797347/4baf2a52-7765-4c73-8a55-283cb64f8a68)

**Comment by tjbck** [comment]
@MarlNox Could you provide browser console logs for this?

**Comment by MarlNox** [comment]
**Console Log when clicking the Pipelines in Admin Settings:** 

Array []
  length: 0
  <prototype>: Array []
    at: function at()
    concat: function concat()
    constructor: function Array()
    copyWithin: function copyWithin()
    entries: function entries()
    every: function every()
    fill: function fill()
    filter: function filter()
    find: function find()
    findIndex: function findIndex()
    findLast: function findLast()
    findLastIndex: function findLastIndex()
    flat: function flat()
    flatMap: function flatMap()
    forEach: function forEach()
    includes: function includes()
    indexOf: function indexOf()
    join: function join()
    keys: function keys()
    lastIndexOf: function lastIndexOf()
    length: 0
    map: function map()
    pop: function pop()
    push: function push()
    reduce: function reduce()
    reduceRight: function reduceRight()
    reverse: function reverse()
    shift: function shift()
    slice: function slice()
    some: function some()
    sort: function sort()
    splice: function splice()
    toLocaleString: function toLocaleString()
    toReversed: function toReversed()
    toSorted: function toSorted()
    toSpliced: function toSpliced()
    toString: function toString()
    unshift: function unshift()
    values: function values()
    with: function with()
    Symbol(Symbol.iterator): function values()
    Symbol(Symbol.unscopables): Object { at: true, copyWithin: true, entries: true, ... }
    <prototype>: Object { ... }

Pipelines.svelte:144:10



**Console logs when refreshing admin page:** 
Source map error: No sources are declared in this source map.
Resource URL: http://localhost:8080/_app/immutable/chunks/languages.67709210.js
Source Map URL: languages.67709210.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:8080/_app/immutable/chunks/translation.516f4a75.js
Source Map URL: translation.516f4a75.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:8080/_app/immutable/nodes/5.9d96acff.js
Source Map URL: 5.9d96acff.js.map

**Comment by tjbck** [comment]
Could you share how you added the pipelines in Settings > Connections? It requires you to put an API Key in order to manage pipelines. 

> API_KEY = os.getenv("PIPELINES_API_KEY", "0p3n-w3bu!")

**Comment by MarlNox** [comment]
Accidentally deleted my logs so reposting them:
Source map error: No sources are declared in this source map.
Resource URL: http://localhost:8080/_app/immutable/chunks/languages.67709210.js
Source Map URL: languages.67709210.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:8080/_app/immutable/chunks/translation.516f4a75.js
Source Map URL: translation.516f4a75.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:8080/_app/immutable/nodes/5.9d96acff.js
Source Map URL: 5.9d96acff.js.map

Array []
  length: 0
  <prototype>: Array []
    at: function at()
    concat: function concat()
    constructor: function Array()
    copyWithin: function copyWithin()
    entries: function entries()
    every: function every()
    fill: function fill()
    filter: function filter()
    find: function find()
    findIndex: function findIndex()
    findLast: function findLast()
    findLastIndex: function findLastIndex()
    flat: function flat()
    flatMap: function flatMap()
    forEach: function forEach()
    includes: function includes()
    indexOf: function indexOf()
    join: function join()
    keys: function keys()
    lastIndexOf: function lastIndexOf()
    length: 0
    map: function map()
    pop: function pop()
    push: function push()
    reduce: function reduce()
    reduceRight: function reduceRight()
    reverse: function reverse()
    shift: function shift()
    slice: function slice()
    some: function some()
    sort: function sort()
    splice: function splice()
    toLocaleString: function toLocaleString()
    toReversed: function toReversed()
    toSorted: function toSorted()
    toSpliced: function toSpliced()
    toString: function toString()
    unshift: function unshift()
    values: function values()
    with: function with()
    Symbol(Symbol.iterator): function values()
    Symbol(Symbol.unscopables): Object { at: true, copyWithin: true, entries: true, ... }
    <prototype>: Object { ... }

Pipelines.svelte:144:10

**Comment by MarlNox** [comment]
> Could you share how you added the pipelines in Settings > Connections? It requires you to put an API Key in order to manage pipelines. 
> 
> > API_KEY = os.getenv("PIPELINES_API_KEY", "0p3n-w3bu!")
> 

I left the api key blank. Should i put this new api key?

**Comment by tjbck** [comment]
@MarlNox `0p3n-w3bu!` is the default API Key if you haven't configured it yourself.

**Comment by MarlNox** [comment]
> @MarlNox `0p3n-w3bu!` is the default API Key if you haven't configured it yourself.

Currently i havent changed anything. Ill try putting it explicitly on the Settings menu, and report back.

**Comment by MarlNox** [comment]
It worked. Explicitly setting the API key allowed for the Admin Settings Pipelines to successfully connect. 
I set up the filter pipeline as demo. 

Testing it further, I'm noticing, that when I chat with a model, the Pipeline doesn't receive any requests. Any further set up required for the pipeline to process chats?
