### ISSUE TITLE
issue with /examples/pipelines/providers/anthropic_manifold_pipeline.py

### ISSUE THREAD

**Issue by NicolasDWolfwood** [open-webui/pipelines#190]
The Anthropic pipeline no longer works with the latest pull. I see it's changed in the last 2 days, but the pipeline is no longer detected and it shows up in the failed folder. Reverting to the previous version makes the pipeline working again.

Happy to help in any way, but I'm not that code savvy unfort.

**Comment by justinh-rahb** [comment]
See:
- #166 

Re-install it by putting the raw URL into your `PIPELINES_URLS` environment variable, the server will pull it and install dependency `sseclient-py` automatically on startup:
```
https://raw.githubusercontent.com/open-webui/pipelines/anthropic-fix/examples/pipelines/providers/anthropic_manifold_pipeline.py
```

#### Two options for doing so:

**Bind mount the `pipelines` volume:**
```sh
docker run -d \
  -p 9099:9099 \
  --add-host=host.docker.internal:host-gateway \
  -v /home/your-username/pipelines:/app/pipelines \
  --name pipelines \
  --restart always \
  ghcr.io/open-webui/pipelines:main
```
You can then drop the `anthropic_manifold_pipeline.py` file in the `pipelines` dir, restart the container, and it should install.

**Alternatively, use the `PIPELINES_URLS` environment variable:**
```sh
docker run -d \
  -p 9099:9099 \
  --add-host=host.docker.internal:host-gateway \
  -v pipelines:/app/pipelines \
  -e PIPELINES_URLS="github_raw_urls;separated_by_semicolons"
  --name pipelines \
  --restart always \
  ghcr.io/open-webui/pipelines:main
```
This should install the depends immediately after downloading the pipeline when the container starts.

**Comment by rfernandez760** [comment]
https://raw.githubusercontent.com/open-webui/pipelines/anthropic-fix/examples/pipelines/providers/anthropic_manifold_pipeline.py

Shows a failed to download file?

**Comment by justinh-rahb** [comment]
Try https://raw.githubusercontent.com/open-webui/pipelines/main/examples/pipelines/providers/anthropic_manifold_pipeline.py

**Comment by rfernandez760** [comment]
It states the pipeline has downloaded successfully, but Anthropic models do have show up in the models drop down, nor does it show up in the pipeline valves section.

**Comment by justinh-rahb** [comment]
See the earlier post about installation, it can't be done by just putting the URL into the Pipelines settings anymore, you need to use environment variables when running the container.

**Comment by rfernandez760** [comment]
Thanks @justinh-rahb. I was able to add the URL to the pipeline command.
