### ISSUE TITLE
feat: Implement Request Throttling for User Accounts

### ISSUE THREAD

**Issue by silentoplayz** [open-webui/pipelines#20]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't any way to set limits on the number of requests that can be made to the large language models (LLMs) within a given time period for each user account. This could lead to abuse and unfair usage of the LLMs.

**Describe the solution you'd like**
I would like Open WebUI to have the ability to set limits on the number of requests that can be made to the LLMs within a given time period for each user account. This feature would help prevent abuse and ensure fair usage of the LLMs. The feature should allow admins to set custom throttle rates for each user account, depending on their needs. When a user reaches their throttle limit, a message should be displayed indicating that they have exceeded their request limit and to try again later, possibly indicating the time in which they can try again.

**Describe alternatives you've considered**
I have considered manually monitoring and limiting user requests, but this would not provide a scalable or automated solution and would require manual intervention.

**Additional context**
I propose implementing request throttling for user accounts to prevent abuse and ensure fair usage of the LLMs. Admins should be able to set the values of X, Y, Z, and T through the WebUI for request throttling per user. Additionally, it might be helpful to provide default values or recommended values based on best practices or common usage patterns.

**Here are some suggested rate limit rules for the request throttling feature:**

- The rate limit is set to X requests per minute and Y requests per hour, operating simultaneously. Whichever limit is reached first triggers the rate limit: if you make more than X requests in any single minute, the per-minute limit applies; if you spread out the requests but exceed Y within an hour without breaching the per-minute cap, then the hourly limit comes into effect.
- Alternatively, a sliding window rate limit could be set, where the limit is reset after a certain period of time. For example, you could set a limit of Z requests per sliding window of T minutes. This means that if a user makes Z requests within a T-minute period, they will be rate limited until T minutes have passed since their first request.

**These are just a few examples, and the actual rate limit rules will depend on your specific use case and the resources available. The key is to find a balance between preventing abuse and ensuring fair usage, while still allowing users to make sufficient requests to accomplish their tasks.**

**Comment by justinh-rahb** [comment]
The rate limit filter works but it would be more ideal if we could set whom will be limited. I (as the admin) don't like that I'm subject to my own rate-limits 🤣

**Comment by NightMachinery** [comment]
The limits should be settable per user. I want different limits for different users.
