### ISSUE TITLE
Issue with markdown

### ISSUE THREAD

**Issue by shadowfaxproject** [open-webui/pipelines#241]
### Discussed in https://github.com/open-webui/pipelines/discussions/233

<div type='discussions-op-text'>

<sup>Originally posted by **shadowfaxproject** August 18, 2024</sup>
I have noticed certain markdown syntax does not render correctly when using pipelines in open_webui.
Specifically noticed this when using pipelines with open_webui 0.3.12/13. 

e.g. following markdown code `[![Test](/favicon.png)](https://google.com)`
**works with open_webui 0.3.10** displays the image and the link to google.com works as expected
<img width="200" alt="Screenshot 2024-08-18 at 6 56 43 PM" src="https://github.com/user-attachments/assets/887dab98-c84a-457e-9d75-793d7c3d7dfd">

**With open_webui 0.3.13**, here is the output rendered, does not display the image. Link to google.com works as expected.

<img width="300" alt="Screenshot 2024-08-18 at 7 26 32 PM" src="https://github.com/user-attachments/assets/c845c1c7-ada9-4401-b94e-6fed0ab32abf">

Has anyone experienced this? I am unable to higher open_webui version because of this.
</div>

**Comment by justinh-rahb** [comment]
Make sure you're testing with latest versions of things. WebUI is at 0.3.16 now.

**Comment by shadowfaxproject** [comment]
Tested it again with 0.3.16 webui and still the same issue.

I will open the issue with open-webui since looks like it's on that side
rather than core pipelines issue.

**Comment by shadowfaxproject** [comment]
Moving this to open-webui https://github.com/open-webui/open-webui/discussions/5057
