### ISSUE TITLE
Q: Best Approach for running RAG searches using pipelines on documents/collections in OpenWebUI

### ISSUE THREAD

**Issue by MarlNox** [open-webui/pipelines#25]
What would be the suggested approach to query the documents that OpenWebUI already has in memory? Currently, I'm "copying" the approach from the Apps/RAG section of the web UI, but it feels quite heavy (had to transplant lot of files/modules to pipelines to make it work), and fails to fetch collections by names, unless i put the hashed name in the search. 

What would be a better way to conduct rag on the current documents we have on openwebui?

**Comment by tjbck** [comment]
Related https://github.com/open-webui/pipelines/issues/9, Let's continue our discussion there!
