### ISSUE TITLE
Unable to use models with / in their names

### ISSUE THREAD

**Issue by nason** [open-webui/pipelines#251]
I have a model hosted with sglang with a name like nason/my-model-v1, and a pipeline named my_pipeline that invokes this model

/models shows the model correctly with an id of my_pipeline.nason/my-model-v1, but requests to /my_pipeline.nason/my-model-v1/filter/inlet return a 404

I believe this is an issue (https://github.com/fastapi/fastapi/discussions/7328) with path parameters in FastAPI https://github.com/open-webui/pipelines/blob/d4fca4c37c4b8603be7797245e749e9086f35130/main.py#L588-L590 

Do you have any suggestions? Are model names with / characters supported?

**Comment by tjbck** [comment]
ids should not contain '/' and other reserved special characters.
