### ISSUE TITLE
Pipeline overriding two simultaneos requests.

### ISSUE THREAD

**Issue by Tavernari** [open-webui/pipelines#266]
Basically, I have two accounts on my OpenWebUI.
The first account calls my pipeline, then the second account also calls it but the second user responds faster than the first, so the first user also receives the message requested by the second user instead of the user 1 request.
How to avoid that?

My pipeline: https://github.com/Tavernari/openwebui-pipelines/blob/main/o1-reasoning.py

**Comment by Tavernari** [comment]
For future same issue, the problem is because I was saving things on self, and since it shares the instance, it was messing with my algorithm.

**Comment by Panicum** [comment]
@Tavernari 
And how did you manage to fix it and still save some "context" for the users and don't use ".self"/don't mix their conversations?

**Comment by sir3mat** [comment]
follow
