### ISSUE TITLE
langfuse_filter_pipeline.py 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by sao-coding** [open-webui/pipelines#267]
langfuse_filter_pipeline.py is error

'str' object has no attribute 'get'

![image](https://github.com/user-attachments/assets/72740089-5710-4ac9-869e-7bde1b90f1c7)
![image](https://github.com/user-attachments/assets/42a5263e-8fcf-46f8-aec2-77ae8099235d)
![image](https://github.com/user-attachments/assets/49fb0262-6f90-4d45-870a-acdef72268f3)

**Comment by baguilartech** [comment]
This is a workaround, I have a self-hosted LangFuse instance and was running into the same error in the UI and in my docker container.

I uploaded this .py to open-webui and replaced it in the pipelines container folder as well: https://github.com/karaketir16/openwebui-langfuse/blob/master/example/langfuse_filter_pipeline.py

![image](https://github.com/user-attachments/assets/42bf622f-d9e2-4e48-a75b-fec230109952)

**Comment by marcklingen** [comment]
-- langfuse maintainer here

This is not an issue that we see across integrations, happy to help with resolution of this issue.

**Comment by rossm-mf** [comment]
I got the same issue with latest pipelines using the v1.3 found here https://raw.githubusercontent.com/open-webui/pipelines/refs/heads/main/examples/filters/langfuse_filter_pipeline.py

it seems that the workaround is aiming at older version of the filter v1.1 https://raw.githubusercontent.com/karaketir16/openwebui-langfuse/refs/heads/master/example/langfuse_filter_pipeline.py

what ever was posted on the main repo as example then is not properly working with the latest langfuse

**Comment by rossm-mf** [comment]
I looked around and it seems to be this line `info = assistant_message.get("info", {})`

the assistant message has not attribut info. only a string on message

**Comment by marcklingen** [comment]
@sao-coding can you check whether this issue is fixed with the latest version of the example?

**Comment by rossm-mf** [comment]
I can confirm on my side already

**Comment by marcklingen** [comment]
awesome, glad that it works again. this was on me, broke this with my latest edit to the example. Now the token counts should be tracked correctly to support cost tracking in Langfuse for openwebui usage
