### ISSUE TITLE
example: conversation turn limit filter

### ISSUE THREAD

**Issue by justinh-rahb** [open-webui/pipelines#31]
**Description:**

Conversations in our can get expensive quickly due to paid API costs. To mitigate this, I propose adding a filter plugin that limits the number of turns in a conversation.

**Problem:**

Long conversations = exponential API cost increases

**Solution:**

A "Turn Limiter" plugin that:

* Sets a max number of turns (e.g., 10, 20)
* Closes or archives conversations when the limit is reached?
* Notifies users to start a new convo

**Benefits:**

* Reduced API costs

**Comment by tjbck** [comment]
Implemented!
