### ISSUE TITLE
feat: language translation layer

### ISSUE THREAD

**Issue by rvsh2** [open-webui/pipelines#4]
**Is your feature request related to a problem? Please describe.**
The problem with many models is that they are good only in english language.

**Describe the solution you'd like**
There could be additional layers for translation:
INPUT: Translation model from any language to English
MIDDLE: Intent model (eg. ChatGpt, ollama models)
OUTPUT: Translation model from English to any language
This would be groundbreaking functionality because many models have trouble with other languages than english.

For example this model could be used for translation:
https://huggingface.co/facebook/mbart-large-50-many-to-many-mmt

**Describe alternatives you've considered**
No alternatives for now.

**Additional context**

**Comment by tcztzy** [comment]
This is some kind like a `middleware` in `fastapi`/`django`

**Comment by tjbck** [comment]
@tcztzy pipeline `filter` type has been added to exactly allow this.

![image](https://github.com/open-webui/pipelines/assets/25473318/4b66a711-c12f-4c63-af7d-bdce71fda7da)

**Comment by tcztzy** [comment]
> @tcztzy pipeline `filter` type has been added to exactly allow this. Compatible with Open WebUI latest dev!
> 
> ![image](https://private-user-images.githubusercontent.com/25473318/334569169-ea350579-9813-4b9c-b85d-bc7c73b7ecf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjkxOTEsIm5iZiI6MTcxNjk2ODg5MSwicGF0aCI6Ii8yNTQ3MzMxOC8zMzQ1NjkxNjktZWEzNTA1NzktOTgxMy00YjljLWI4NWQtYmM3YzczYjdlY2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA3NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3NmIzOGRkMDkwMzQ4MWFkOWFjNjEwMTc5ZGExMzFiYWZhNDIwMWQ4YWY2ZWI2NjIwYjA4ZmVlY2I1NzU1MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qp1lM9mQf6ydP_YzV3gintFM_y83kc9X_C0uOH9RePs)
> 
> ![workflow](https://private-user-images.githubusercontent.com/25473318/334575273-3b8424fe-d6d4-4111-805b-8c50e9164c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjkxOTEsIm5iZiI6MTcxNjk2ODg5MSwicGF0aCI6Ii8yNTQ3MzMxOC8zMzQ1NzUyNzMtM2I4NDI0ZmUtZDZkNC00MTExLTgwNWItOGM1MGU5MTY0YzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDA3NDgxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExM2M4Y2RhZTNiN2Y3NGYwMTllMzVjNTExMDA0M2M4ODg1YWVlYWNiZmQ0YzU4YzYyZTQ4NDhhOTA4ZGMxNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1ZfCmlA4SfVYC5XwESEOKKlxWFZlK0kffFJ2PUKs2E)

I am working on paper writing recently, will have time to realize it early june.

**Comment by tjbck** [comment]
Implemented with `filter` pipeline using `inlet`, and `outlet` hooks!

https://github.com/open-webui/pipelines/assets/25473318/4f818d72-adca-4ed0-a2e7-c5d061236f2d



https://github.com/open-webui/pipelines/blob/main/pipelines/examples/libretranlsate_filter_pipeline.py

**Comment by rvsh2** [comment]
That's look amazing - will test it right away :)

**Comment by rvsh2** [comment]
I've installed libretranslate - working fine.
I made a docker for pipelines - working fine on port 9099.
<img width="566" alt="image" src="https://github.com/open-webui/pipelines/assets/32043169/663f98df-1e66-444a-a4a4-0d340f9fde6d">

<img width="641" alt="image" src="https://github.com/open-webui/pipelines/assets/32043169/30defa16-558c-4de7-a8da-143f2c383235">


But I don't have pipelines in Admin settings.
<img width="563" alt="image" src="https://github.com/open-webui/pipelines/assets/32043169/1adf949a-05ef-4e2b-bfd8-08dbaab8d4c6">


Open webui Version seems to be the latest - v0.1.125 (latest)
How to activate pipelines options in open webui?

P.S. if someone need a dockerfile for pipelines I've attached one.
[pipelines-docker.zip](https://github.com/open-webui/pipelines/files/15501954/pipelines-docker.zip)

**Comment by justinh-rahb** [comment]
@rvsh2 Pipelines support in the UI is only in `dev` branch right now, pull the `dev` Docker image tag.

**Comment by rvsh2** [comment]
OK, I managed it to work. It looks very nice. I will try to test it more.

**Comment by rvsh2** [comment]
Ok It works very good. No bugs :)  but I'm thinking about the concept and do you think there is a possiblity that libretranslate will only translate relevant information for example:
let's ask llama3: **Write a simple python script that counts from 1 to 100 (no more than 4 sentences)**
```
USER: Napisz prosty skrypt w python liczacy od 1 do 100 (nie więcej niż 4 zdania(
ASSISTANT WITH TRANSLATED OUTPUT TO POLISH: 
llama3:latest 6:00 PM
Oto prosty skrypt Pythona, który liczy się od 1 do 100:
"'
dla i w zakresie (1, 101):
druk (i)
"'
```
I don't know libre translate well, for example can it decide to not translate code section somehow?

**Comment by tjbck** [comment]
Related: https://github.com/open-webui/open-webui/issues/2152

Should be relatively easy, PR welcome!
