### ISSUE TITLE
feat: Keeping Threads of Conversatiosn separate in interactions

### ISSUE THREAD

**Issue by MarlNox** [open-webui/pipelines#49]
It seems that the pipes, will take any input from any of the chat windows, and will "merge" the content in the backend. 
We need to keep the conversation threads separate, so that there's no cross sending of messages or mixup of threads. 

We need a method to identify the conversation threads, and keep them separate.

**Comment by tjbck** [comment]
Not entirely understanding your use case but `chat_id` gets sent by Open WebUI!

**Comment by MarlNox** [comment]
I was using the OpenAI pipeline in the examples and it wasnt sending any data on the chat_id.
Using the api does, im currently streamlining the responses to the frontend.
