### ISSUE TITLE
Piplines Install & Run (Guide)

### ISSUE THREAD

**Issue by rootcli** [open-webui/pipelines#61]
Apologies for placing it in here, but figured that where people needed the most help.

I created this little guide to help newbies Run pipelines, as it was a challenge for me to install and run pipelines. Hope it helps.

##### Quick Start with Docker
[Pipelines Repository Quick Guide](https://github.com/open-webui/pipelines/tree/main#-quick-start-with-docker)

## What to do Next?

1. *Run the Pipelines container:*
    
2. *Login to Open WebUI:*
    - Navigate to the **Settings > Connections > OpenAI API** section in Open WebUI.
    - Set the API URL to `http://localhost:9099` and the API key to `0p3n-w3bu!`. Your pipelines should now be active. IF localhost doesn't work use `host.docker.internal`

 3. *You can Download the examples folder (or individual files, as you wish) from the Pipelines repository:*
 
 `To Download the Examples Folder:
```bash
git clone https://github.com/open-webui/pipelines.git examples
```

`Here we will perform an example on one file which is called wikipedia_pipeline.py you can direct download it to linux from the link below`
```shell
curl -O https://raw.githubusercontent.com/open-webui/pipelines/c9766d630ab69549b06e994b39fb173a61bb82e8/examples/pipelines/integrations/wikipedia_pipeline.py
```

4. Place The downloaded file `wikipedia_pipeline.py` in **pipelines Root Folder.**

2. *In the open webui interface Go to Admin Panel > Gear Icon in top right ⚙ > pipelines*

	you should see `Pipelines Valves` click on the pulldown menu and select `wikipedia_pipeline` 
<img width="861" alt="Pasted image 20240605090833" src="https://github.com/open-webui/pipelines/assets/94934393/3d18818a-3a9d-49e7-8d7f-8d5ed55a864a">

3. Go to New Chat > From the Models pulldown Menu select ``
<img width="968" alt="Pasted image 20240605091159" src="https://github.com/open-webui/pipelines/assets/94934393/c36de630-6e38-4e73-baba-479077d6dbef">

4. Now type a topic you wish to search from `wikipedia

**Comment by justinh-rahb** [comment]
Much appreciated! I'm going to move this to discussions and perhaps we can pin it. Eventually we'll get this sort of stuff committed into the docs proper.

**Comment by rootcli** [comment]
Yes, I did 😂

**Comment by alex13by** [comment]
How do you get more pipes? I want to know how it works

**Comment by Derjyn** [comment]
I'm not seeing anything anywhere about API key outside of the `0p3n-w3bu!`, which doesn't work. I've poured over documentation, and nothing... Can't leave the field blank, and the example key doesn't seem to work.

**Comment by justinh-rahb** [comment]
We've added a number of new pages for Pipelines, Functions, and Tools to the docs recently, and more will be committed still. Closing this now as it's served its purpose, thanks everyone.
