### ISSUE TITLE
[Feature request] Add pipeline script over file browser

### ISSUE THREAD

**Issue by Fusseldieb** [open-webui/pipelines#63]
It would be nice if we had a button to browse local scripts from the device, which can then be uploaded. This would be much "easier" than trying to access the "pipeline/" docker mount to push a file or upload a script to GitHub.

Just a suggestion :) 

![image](https://github.com/open-webui/pipelines/assets/4715129/e6b07a27-b429-4be8-ace8-8fdec6919f12)

**Comment by tjbck** [comment]
so basically an upload feature? 😅 Coming soon 🫡

**Comment by tjbck** [comment]
<img width="803" alt="image" src="https://github.com/open-webui/pipelines/assets/25473318/8aa9e358-5af0-4fa6-8423-d44ca394dbef">

Added on dev!

**Comment by Fusseldieb** [comment]
Oh wow, that was fast! You're amazing. Thank you!
