### ISSUE TITLE
feat: add guardrail example

### ISSUE THREAD

**Issue by tjbck** [open-webui/pipelines#7]
(e.g. detect toxicity -> if toxic == True: return "I cannot help you with that")

**Comment by mkhludnev** [comment]
Pardon. It might be obvious, but how to detect toxicity? Just a hell bunch of regexps?

**Comment by tjbck** [comment]
We could probably use another LLM pipeline to detect 😅 or use something like https://github.com/unitaryai/detoxify

**Comment by tjbck** [comment]
https://github.com/open-webui/pipelines/blob/main/pipelines/examples/detoxify_filter_pipeline.py

@mkhludnev  Just added here, feel free to try it out and let me know if you encounter any issues!
