### ISSUE TITLE
Anthropic models added by pipelines for some reason does not works in models (agents)

### ISSUE THREAD

**Issue by derevyan** [open-webui/pipelines#84]
# Bug Report

## Description

**Bug Summary:**
Anthropic models added by pipelines for some reason does not works in models(agents).

**Steps to Reproduce:**
Im add Anthropic models using pipelines.
https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/anthropic_manifold_pipeline.py
Models in chat mode works just fine, but when im try to create a model(agent) with anthropic llm selected im get this error: 
```aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>```
All other models works fine, google models added same way (pipelines) also works great. Don't really understand where to look to fix it, any ideas will be very helpful.

**Expected Behavior:**
[Describe what you expected to happen.]

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
v0.3.2

- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
Ubuntu 20.04

- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
aiohttp.client_exceptions.ClientPayloadError: Response payload is not completed: <TransferEncodingError: 400, message='Not enough data for satisfy transfer length header.'>

**Screenshots (if applicable):**
![Screenshot 2024-06-12 at 19 46 01](https://github.com/open-webui/open-webui/assets/21168331/4693ee88-714b-47e3-a436-2178febd34e3)

## Installation Method
Docker compose

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by ProjectMakersDE** [comment]
I'm experiencing the same issue as described here.

I have installed the pipeline in Docker, just like the webui, but I'm using http://127.0.0.1:9099/ as the pipeline address since http://host.docker.internal:9099/ doesn't work for me. Despite this change, I'm still encountering the same error.

I would greatly appreciate any assistance or suggestions on how to resolve this issue. Please let me know if you need any additional information or details about my setup.

Thank you in advance for your help!

**Comment by ProjectMakersDE** [comment]
I would like to note that the issue still persists even with the version updated yesterday. Additionally, the following points have come to our attention:

- The chat itself encounters a Network Error and does not reach the API.
- **However, the title is successfully generated with Anthropic (this can be observed in the API log from Anthropic).**
